version: "3.9"

services:
  test_db_pythonweb:
    image: postgres:latest
    container_name: test_db_pythonweb
    restart: no
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env.test
