version: "3.9"

services:
  test_postgresdb:
    image: postgres:latest
    container_name: test_postgresdb
    restart: no
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres=value

  test_redisdb:
    image: redis:7.4
    command: redis-server --appendonly yes
    container_name: test_redisdb
    restart: no
    ports:
      - "6379:6379"
    expose:
      - "6379"
