version: "3.9"

services:
  test_db_pythonweb:
    image: postgres:latest
    container_name: test_db_pythonweb
    restart: no
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres=value
